// Generated by BUCKLESCRIPT VERSION 4.0.0, PLEASE EDIT WITH CARE
'use strict';


function execute(argString) {
  return argString + "Impl";
}

var ServiceComponentImpl = /* module */[/* execute */execute];

function execute$1(argString) {
  return argString + "Mock";
}

var ServiceComponentMock = /* module */[/* execute */execute$1];

function execute$2(argString) {
  return argString + "MockFile";
}

exports.ServiceComponentImpl = ServiceComponentImpl;
exports.ServiceComponentMock = ServiceComponentMock;
exports.execute = execute$2;
/* No side effect */
