// Generated by BUCKLESCRIPT VERSION 4.0.0, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var DiComponent$ReactTemplate = require("./DiComponent.bs.js");
var DependencyInjection$ReactTemplate = require("./DependencyInjection.bs.js");

var RealService = DependencyInjection$ReactTemplate.ServiceFunctor(DiComponent$ReactTemplate.ServiceComponentImpl);

var MockService = DependencyInjection$ReactTemplate.ServiceFunctor(DiComponent$ReactTemplate.ServiceComponentMock);

var MockFileUnitService = DependencyInjection$ReactTemplate.ServiceFunctor([DiComponent$ReactTemplate.execute]);

var RealApplication = DependencyInjection$ReactTemplate.Application(MockFileUnitService);

var result = Curry._1(RealApplication[/* run */0], "run");

console.log(result);

exports.RealService = RealService;
exports.MockService = MockService;
exports.MockFileUnitService = MockFileUnitService;
exports.RealApplication = RealApplication;
/* RealService Not a pure module */
