// Generated by BUCKLESCRIPT VERSION 4.0.0, PLEASE EDIT WITH CARE
'use strict';

var Caml_exceptions = require("bs-platform/lib/js/caml_exceptions.js");

var Id = Caml_exceptions.create("HeaderUser-ReactTemplate.Id");

var Name = Caml_exceptions.create("HeaderUser-ReactTemplate.Name");

var Age = Caml_exceptions.create("HeaderUser-ReactTemplate.Age");

var Gender = Caml_exceptions.create("HeaderUser-ReactTemplate.Gender");

exports.Id = Id;
exports.Name = Name;
exports.Age = Age;
exports.Gender = Gender;
/* No side effect */
