// Generated by BUCKLESCRIPT VERSION 4.0.0, PLEASE EDIT WITH CARE
'use strict';

var Caml_exceptions = require("bs-platform/lib/js/caml_exceptions.js");

var Id = Caml_exceptions.create("HeaderSoftwear-ReactTemplate.Id");

var Name = Caml_exceptions.create("HeaderSoftwear-ReactTemplate.Name");

var Author = Caml_exceptions.create("HeaderSoftwear-ReactTemplate.Author");

var CreatedAt = Caml_exceptions.create("HeaderSoftwear-ReactTemplate.CreatedAt");

exports.Id = Id;
exports.Name = Name;
exports.Author = Author;
exports.CreatedAt = CreatedAt;
/* No side effect */
