// Generated by BUCKLESCRIPT VERSION 4.0.0, PLEASE EDIT WITH CARE
'use strict';

var Caml_exceptions = require("bs-platform/lib/js/caml_exceptions.js");

var A = Caml_exceptions.create("ReportHeader-ReactTemplate.A");

var B = Caml_exceptions.create("ReportHeader-ReactTemplate.B");

var C = Caml_exceptions.create("ReportHeader-ReactTemplate.C");

var D = Caml_exceptions.create("ReportHeader-ReactTemplate.D");

var E = Caml_exceptions.create("ReportHeader-ReactTemplate.E");

var F = Caml_exceptions.create("ReportHeader-ReactTemplate.F");

exports.A = A;
exports.B = B;
exports.C = C;
exports.D = D;
exports.E = E;
exports.F = F;
/* No side effect */
