// Generated by BUCKLESCRIPT VERSION 4.0.0, PLEASE EDIT WITH CARE
'use strict';

var List = require("bs-platform/lib/js/list.js");
var Curry = require("bs-platform/lib/js/curry.js");
var Caml_exceptions = require("bs-platform/lib/js/caml_exceptions.js");

function getWidthSize(size) {
  if (typeof size === "number") {
    switch (size) {
      case 0 : 
          return 7.0;
      case 1 : 
          return 9.5;
      case 2 : 
          return 12.0;
      
    }
  } else {
    return size[0];
  }
}

var A = Caml_exceptions.create("ReportHeader-ReactTemplate.A");

var B = Caml_exceptions.create("ReportHeader-ReactTemplate.B");

var C = Caml_exceptions.create("ReportHeader-ReactTemplate.C");

var D = Caml_exceptions.create("ReportHeader-ReactTemplate.D");

var E = Caml_exceptions.create("ReportHeader-ReactTemplate.E");

var F = Caml_exceptions.create("ReportHeader-ReactTemplate.F");

function headerItemToJs(param) {
  return {
          column: param[/* column */0],
          size: param[/* size */1],
          isSizeFiexed: param[/* isSizeFiexed */2]
        };
}

function headerItemFromJs(param) {
  return /* record */[
          /* column */param.column,
          /* size */param.size,
          /* isSizeFiexed */param.isSizeFiexed
        ];
}

function getHeaderItemWidthSize(headerItem) {
  return getWidthSize(headerItem[/* size */1]);
}

function valueToString(func, value) {
  return JSON.stringify(Curry._1(func, value));
}

function stringFromValue(func, anyString) {
  return Curry._1(func, JSON.parse(anyString));
}

function getWidthSizeByTableWidthSize(tableWidthSize, header) {
  var headerSizeList = List.map(getHeaderItemWidthSize, header);
  var totalHeaderSize = List.fold_left((function (prim, prim$1) {
          return prim + prim$1;
        }), 0.0, headerSizeList);
  if (tableWidthSize > totalHeaderSize) {
    var flexibleSizeHeaderCount = List.length(List.filter((function (header) {
                  return !header[/* isSizeFiexed */2];
                }))(header));
    var totalSizeFiexedWidth = List.fold_left((function (prim, prim$1) {
            return prim + prim$1;
          }), 0.0, List.map(getHeaderItemWidthSize, List.filter((function (header) {
                      return header[/* isSizeFiexed */2];
                    }))(header)));
    var headerSize = (tableWidthSize - totalSizeFiexedWidth) / flexibleSizeHeaderCount;
    return List.map((function (headerItem) {
                  return /* record */[
                          /* column */headerItem[/* column */0],
                          /* size : Free */[headerSize],
                          /* isSizeFiexed */headerItem[/* isSizeFiexed */2]
                        ];
                }), header);
  } else {
    return header;
  }
}

exports.getWidthSize = getWidthSize;
exports.A = A;
exports.B = B;
exports.C = C;
exports.D = D;
exports.E = E;
exports.F = F;
exports.headerItemToJs = headerItemToJs;
exports.headerItemFromJs = headerItemFromJs;
exports.getHeaderItemWidthSize = getHeaderItemWidthSize;
exports.valueToString = valueToString;
exports.stringFromValue = stringFromValue;
exports.getWidthSizeByTableWidthSize = getWidthSizeByTableWidthSize;
/* No side effect */
