// Generated by BUCKLESCRIPT VERSION 4.0.0, PLEASE EDIT WITH CARE
'use strict';

var Block = require("bs-platform/lib/js/block.js");
var Curry = require("bs-platform/lib/js/curry.js");

function applyUser(apply, user) {
  return Curry._1(apply, user[0]);
}

var Sample = /* module */Block.localModule([], []);

exports.applyUser = applyUser;
exports.Sample = Sample;
/* No side effect */
