// Generated by BUCKLESCRIPT VERSION 4.0.0, PLEASE EDIT WITH CARE
'use strict';

var Block = require("bs-platform/lib/js/block.js");
var Validation$ReactTemplate = require("../Validation.bs.js");

var validateText = Validation$ReactTemplate.fromErrors((function (text) {
        if (text.length > 10) {
          return /* :: */Block.simpleVariant("::", [
                    /* TextIsOverMaxLength */0,
                    /* [] */0
                  ]);
        } else {
          return /* [] */0;
        }
      }));

var validateAge = Validation$ReactTemplate.fromErrors((function (age) {
        if (age >= 0) {
          return /* [] */0;
        } else {
          return /* :: */Block.simpleVariant("::", [
                    /* InvalidAge */1,
                    /* [] */0
                  ]);
        }
      }));

var validateName = Validation$ReactTemplate.fromErrors((function (name) {
        if (name === "") {
          return /* :: */Block.simpleVariant("::", [
                    /* InvalidName */0,
                    /* [] */0
                  ]);
        } else {
          return /* [] */0;
        }
      }));

Validation$ReactTemplate.run(validateText, (function (v) {
        return v;
      }), "success!");

exports.validateText = validateText;
exports.validateAge = validateAge;
exports.validateName = validateName;
/* validateText Not a pure module */
