// Generated by BUCKLESCRIPT VERSION 4.0.0, PLEASE EDIT WITH CARE
'use strict';

var Block = require("bs-platform/lib/js/block.js");
var Js_primitive = require("bs-platform/lib/js/js_primitive.js");

function withDefault($$default, op) {
  if (op !== undefined) {
    return Js_primitive.valFromOption(op);
  } else {
    return $$default;
  }
}

var Option = /* module */Block.localModule(["withDefault"], [withDefault]);

function contain(target, search) {
  return new RegExp(search).test(target);
}

var $$String = /* module */Block.localModule(["contain"], [contain]);

exports.Option = Option;
exports.$$String = $$String;
/* No side effect */
