// Generated by BUCKLESCRIPT VERSION 4.0.0, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var React = require("react");
var ReactDOMRe = require("reason-react/src/ReactDOMRe.js");
var ReasonReact = require("reason-react/src/ReasonReact.js");
var Tooltip$ReactTemplate = require("./Tooltip.bs.js");
var ModalSample$ReactTemplate = require("./ModalSample.bs.js");
var PromiseWrapper$ReactTemplate = require("./PromiseWrapper.bs.js");
var TodoFlexibleTable$ReactTemplate = require("./Samples/TodoFlexibleTable.bs.js");

var IntPromiseWrapperDef = /* module */[];

var IntPromiseWrapper = PromiseWrapper$ReactTemplate.PromiseWrapper(IntPromiseWrapperDef);

function whenSuccess(v) {
  return React.createElement("div", undefined, String(v));
}

function whenError() {
  return React.createElement("div", undefined, React.createElement("p", undefined, "ERROR!"));
}

var whenPending = React.createElement("div", undefined, React.createElement("p", undefined, "NowLoading..."));

function r() {
  return /* () */0;
}

function timePromise(count) {
  return new Promise((function (resolve, _) {
                setTimeout((function () {
                        return resolve(count);
                      }), count);
                return /* () */0;
              }));
}

ReactDOMRe.renderToElementWithId(React.createElement("div", undefined, ReasonReact.element(undefined, undefined, Tooltip$ReactTemplate.make(/* Down */2, /* Large */2, "IAM TOOLTIP", React.createElement("button", {
                      className: "target"
                    }, "HELLO"), /* array */[])), ReasonReact.element(undefined, undefined, TodoFlexibleTable$ReactTemplate.TodoTableSample[/* make */3](/* array */[])), ReasonReact.element(undefined, undefined, Curry._5(IntPromiseWrapper[/* make */1], timePromise(1000), whenSuccess, whenError, whenPending, /* array */[])), ReasonReact.element(undefined, undefined, ModalSample$ReactTemplate.make(/* array */[]))), "index");

function add(x, y, z) {
  return (x + y | 0) + z | 0;
}

var addFiveOops = add(5, 4, 4);

function add2(x, y, z) {
  return (x + y | 0) + z | 0;
}

var addFiveOops2 = add2(5, 4, 4);

function add3(x, y, z) {
  return (x + y | 0) + z | 0;
}

var PromiseWrapper = PromiseWrapper$ReactTemplate.PromiseWrapper;

var addFiveOops3 = 13;

exports.PromiseWrapper = PromiseWrapper;
exports.IntPromiseWrapperDef = IntPromiseWrapperDef;
exports.IntPromiseWrapper = IntPromiseWrapper;
exports.whenSuccess = whenSuccess;
exports.whenError = whenError;
exports.whenPending = whenPending;
exports.r = r;
exports.timePromise = timePromise;
exports.add = add;
exports.addFiveOops = addFiveOops;
exports.add2 = add2;
exports.addFiveOops2 = addFiveOops2;
exports.add3 = add3;
exports.addFiveOops3 = addFiveOops3;
/* IntPromiseWrapper Not a pure module */
