// Generated by BUCKLESCRIPT VERSION 4.0.0, PLEASE EDIT WITH CARE
'use strict';

var Block = require("bs-platform/lib/js/block.js");
var React = require("react");
var ReasonReact = require("reason-react/src/ReasonReact.js");
var ReactHelper$ReactTemplate = require("./ReactHelper.bs.js");

var component = ReasonReact.statelessComponent("ModalComponent");

function modalSizeToAttr(size) {
  switch (size) {
    case 0 : 
        return "modal-lg";
    case 1 : 
        return "modal-sm";
    case 2 : 
        return "";
    
  }
}

var modalOpenStyle = {
  display: "block",
  left: "0",
  position: "fixed",
  right: "0",
  top: "0",
  visibility: "visible",
  zIndex: "1050",
  opacity: "1",
  transition: "all 0.5s"
};

var modalHiddenStyle = {
  bottom: "auto",
  display: "block",
  position: "fixed",
  top: "-100vh",
  visibility: "hidden",
  zIndex: "1050",
  opacity: "1",
  transition: "all 0.5s",
  pointerEvents: "none"
};

var modalBgStyle = {
  backgroundColor: "rgba(41, 38, 38, 0.5)",
  height: "100%",
  left: "0",
  position: "fixed",
  top: "0",
  width: "100%",
  zIndex: "1049"
};

var modalBgHiddenStyle = { };

function make(hidden, size, onClickContentOutside, header, footer, body, _) {
  return /* record */Block.record([
            "debugName",
            "reactClassInternal",
            "handedOffState",
            "willReceiveProps",
            "didMount",
            "didUpdate",
            "willUnmount",
            "willUpdate",
            "shouldUpdate",
            "render",
            "initialState",
            "retainedProps",
            "reducer",
            "subscriptions",
            "jsElementWrapped"
          ], [
            component[/* debugName */0],
            component[/* reactClassInternal */1],
            component[/* handedOffState */2],
            component[/* willReceiveProps */3],
            component[/* didMount */4],
            component[/* didUpdate */5],
            component[/* willUnmount */6],
            component[/* willUpdate */7],
            component[/* shouldUpdate */8],
            (function () {
                var modalClassName = "modal modal-dialog fade modal-dialog-centered " + modalSizeToAttr(size);
                return ReasonReact.element(undefined, undefined, ReactHelper$ReactTemplate.Fragment[/* make */0](/* array */[
                                React.createElement("div", {
                                      className: modalClassName,
                                      style: hidden ? modalHiddenStyle : modalOpenStyle,
                                      onClick: (function (prim) {
                                          prim.stopPropagation();
                                          return /* () */0;
                                        })
                                    }, React.createElement("div", {
                                          className: "modal-content"
                                        }, ReactHelper$ReactTemplate.option(header), ReactHelper$ReactTemplate.option(body), ReactHelper$ReactTemplate.option(footer))),
                                React.createElement("span", {
                                      style: hidden ? modalBgHiddenStyle : modalBgStyle,
                                      onClick: (function () {
                                          return ReactHelper$ReactTemplate.optionalHandler(onClickContentOutside);
                                        })
                                    })
                              ]));
              }),
            component[/* initialState */10],
            component[/* retainedProps */11],
            component[/* reducer */12],
            component[/* subscriptions */13],
            component[/* jsElementWrapped */14]
          ]);
}

exports.component = component;
exports.modalSizeToAttr = modalSizeToAttr;
exports.modalOpenStyle = modalOpenStyle;
exports.modalHiddenStyle = modalHiddenStyle;
exports.modalBgStyle = modalBgStyle;
exports.modalBgHiddenStyle = modalBgHiddenStyle;
exports.make = make;
/* component Not a pure module */
