// Generated by BUCKLESCRIPT VERSION 4.0.0, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");

function andThen(a, b, v) {
  return Curry._1(b, Curry._1(a, v));
}

function $less$pipe(a, b) {
  return Curry._1(a, b);
}

function always(b, _) {
  return b;
}

function identity(a) {
  return a;
}

var $great$great = andThen;

exports.andThen = andThen;
exports.$great$great = $great$great;
exports.$less$pipe = $less$pipe;
exports.always = always;
exports.identity = identity;
/* No side effect */
