// Generated by BUCKLESCRIPT VERSION 4.0.0, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var Js_primitive = require("bs-platform/lib/js/js_primitive.js");

function option(op) {
  if (op !== undefined) {
    return Js_primitive.valFromOption(op);
  } else {
    return null;
  }
}

function optionalHandler(op) {
  if (op !== undefined) {
    return Curry._1(op, /* () */0);
  } else {
    return /* () */0;
  }
}

exports.option = option;
exports.optionalHandler = optionalHandler;
/* No side effect */
