// Generated by BUCKLESCRIPT VERSION 4.0.0, PLEASE EDIT WITH CARE
'use strict';

var Block = require("bs-platform/lib/js/block.js");
var Curry = require("bs-platform/lib/js/curry.js");
var React = require("react");
var ReasonReact = require("reason-react/src/ReasonReact.js");
var Js_primitive = require("bs-platform/lib/js/js_primitive.js");

function option(op) {
  if (op !== undefined) {
    return Js_primitive.valFromOption(op);
  } else {
    return null;
  }
}

function optionalHandler(op) {
  if (op !== undefined) {
    return Curry._1(op, /* () */0);
  } else {
    return /* () */0;
  }
}

function make(children) {
  return ReasonReact.wrapJsForReason(React.Fragment, { }, children);
}

var Fragment = /* module */Block.localModule(["make"], [make]);

exports.option = option;
exports.optionalHandler = optionalHandler;
exports.Fragment = Fragment;
/* react Not a pure module */


// TODO 移動
function deleteMail() {
	try {
    console.log("start delete click");
	  document.getElementsByClassName("_op_C2 ms-fwt-r ms-fcl-np o365button")[0].click();
	  document.getElementsByClassName("contextMenuDropShadow contextMenuPopup removeFocusOutline")	[0].children[0].children[0].children[0].children[0].children[1].children[0].click();
    document.getElementsByClassName("_fce_W o365button o365buttonOutlined ms-font-m ms-fwt-sb ms-fcl-w ms-bgc-tp ms-bcl-tp ms-bgc-td-f ms-bcl-tdr-f")[0].click();
    console.log("all click done");
    setTimeout(() => deleteMail(), 10000);
	} catch (e) {
    console.log("fail delete click, restart execute");
    setTimeout(() => deleteMail(), 1000);
  }
}