// Generated by BUCKLESCRIPT VERSION 4.0.0, PLEASE EDIT WITH CARE
'use strict';

var Block = require("bs-platform/lib/js/block.js");
var Curry = require("bs-platform/lib/js/curry.js");
var ReasonReact = require("reason-react/src/ReasonReact.js");

function Application(R) {
  var getPageElement = function (page) {
    return page[0];
  };
  var component = ReasonReact.reducerComponent("application");
  var transition = function (send, page, url) {
    var route = Curry._1(R[/* urlToRoute */0], url);
    Curry._1(send, /* StartPageLoading */Block.variant("StartPageLoading", 0, [page[0]]));
    Curry._1(R[/* transition */1], route).then((function (element) {
              return Promise.resolve(Curry._1(send, /* LoadedPage */Block.variant("LoadedPage", 1, [element])));
            })).catch((function (error) {
            Curry._1(send, /* DetectedPageLoadError */Block.variant("DetectedPageLoadError", 2, [error]));
            return Promise.resolve(/* () */0);
          }));
    return /* () */0;
  };
  var make = function (_, initialPage, onError, onStartTransition, onFinishTransition) {
    return /* record */Block.record([
              "debugName",
              "reactClassInternal",
              "handedOffState",
              "willReceiveProps",
              "didMount",
              "didUpdate",
              "willUnmount",
              "willUpdate",
              "shouldUpdate",
              "render",
              "initialState",
              "retainedProps",
              "reducer",
              "subscriptions",
              "jsElementWrapped"
            ], [
              component[/* debugName */0],
              component[/* reactClassInternal */1],
              component[/* handedOffState */2],
              component[/* willReceiveProps */3],
              (function (self) {
                  var partial_arg = self[/* state */1][/* page */0];
                  var partial_arg$1 = self[/* send */3];
                  var id = ReasonReact.Router[/* watchUrl */1]((function (param) {
                          return transition(partial_arg$1, partial_arg, param);
                        }));
                  Curry._1(self[/* onUnmount */4], (function () {
                          return ReasonReact.Router[/* unwatchUrl */2](id);
                        }));
                  return transition(self[/* send */3], self[/* state */1][/* page */0], ReasonReact.Router[/* dangerouslyGetInitialUrl */3](/* () */0));
                }),
              component[/* didUpdate */5],
              component[/* willUnmount */6],
              component[/* willUpdate */7],
              component[/* shouldUpdate */8],
              (function (self) {
                  return self[/* state */1][/* page */0][0];
                }),
              (function () {
                  return /* record */Block.record(["page"], [Block.variant("Loaded", 1, [initialPage])]);
                }),
              component[/* retainedProps */11],
              (function (action, state) {
                  switch (action.tag | 0) {
                    case 0 : 
                        return /* UpdateWithSideEffects */Block.variant("UpdateWithSideEffects", 2, [
                                  /* record */Block.record(["page"], [Block.variant("InTransition", 0, [action[0]])]),
                                  (function () {
                                      return Curry._1(onStartTransition, /* () */0);
                                    })
                                ]);
                    case 1 : 
                        return /* UpdateWithSideEffects */Block.variant("UpdateWithSideEffects", 2, [
                                  /* record */Block.record(["page"], [Block.variant("Loaded", 1, [action[0]])]),
                                  (function () {
                                      return Curry._1(onFinishTransition, /* () */0);
                                    })
                                ]);
                    case 2 : 
                        var error = action[0];
                        return /* UpdateWithSideEffects */Block.variant("UpdateWithSideEffects", 2, [
                                  /* record */Block.record(["page"], [Block.variant("Loaded", 1, [state[/* page */0][0]])]),
                                  (function () {
                                      return Curry._1(onError, error);
                                    })
                                ]);
                    
                  }
                }),
              component[/* subscriptions */13],
              component[/* jsElementWrapped */14]
            ]);
  };
  return /* module */Block.localModule([
            "getPageElement",
            "component",
            "transition",
            "make"
          ], [
            getPageElement,
            component,
            transition,
            make
          ]);
}

exports.Application = Application;
/* ReasonReact Not a pure module */
