// Generated by BUCKLESCRIPT VERSION 4.0.0, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");

function AnimalBook(A) {
  var size = function (t) {
    if (Curry._1(A[/* height */1], t) > 100.0 || Curry._1(A[/* weight */0], t) > 50.0) {
      return /* Big */1;
    } else {
      return /* Small */0;
    }
  };
  return /* module */[/* size */size];
}

exports.AnimalBook = AnimalBook;
/* No side effect */
