// Generated by BUCKLESCRIPT VERSION 4.0.0, PLEASE EDIT WITH CARE
'use strict';

var Block = require("bs-platform/lib/js/block.js");

var ANIMAL = /* module */Block.localModule([], []);

exports.ANIMAL = ANIMAL;
/* No side effect */
