// Generated by BUCKLESCRIPT VERSION 4.0.0, PLEASE EDIT WITH CARE
'use strict';

var Caml_exceptions = require("bs-platform/lib/js/caml_exceptions.js");
var Caml_builtin_exceptions = require("bs-platform/lib/js/caml_builtin_exceptions.js");

var Cat = Caml_exceptions.create("Cat-ReactTemplate.Cat");

function make(cat) {
  return [
          Cat,
          cat
        ];
}

function height(t) {
  if (t[0] === Cat) {
    return t[1][/* height */0];
  } else {
    throw [
          Caml_builtin_exceptions.match_failure,
          /* tuple */[
            "Cat.re",
            16,
            4
          ]
        ];
  }
}

function weight(t) {
  if (t[0] === Cat) {
    return t[1][/* height */0];
  } else {
    throw [
          Caml_builtin_exceptions.match_failure,
          /* tuple */[
            "Cat.re",
            20,
            4
          ]
        ];
  }
}

var CatFun = /* module */[
  /* make */make,
  /* height */height,
  /* weight */weight,
  /* groupName */"Cat"
];

var c_001 = /* record */[
  /* height */100.0,
  /* weight */100.0,
  /* pattern */1
];

var c = [
  Cat,
  c_001
];

exports.Cat = Cat;
exports.CatFun = CatFun;
exports.c = c;
/* No side effect */
