// Generated by BUCKLESCRIPT VERSION 4.0.0, PLEASE EDIT WITH CARE
'use strict';

var AnimalBook$ReactTemplate = require("./AnimalBook.bs.js");

function height(t) {
  return t[/* height */0];
}

function weight(t) {
  return t[/* weight */1];
}

var groupName = "Cat";

var Cat = /* module */[
  /* height */height,
  /* weight */weight,
  /* groupName */groupName
];

var CatBook = AnimalBook$ReactTemplate.AnimalBook([
      weight,
      height,
      groupName
    ]);

var c = /* record */[
  /* height */100.0,
  /* weight */100.0,
  /* pattern */1
];

exports.Cat = Cat;
exports.c = c;
exports.CatBook = CatBook;
/* CatBook Not a pure module */
