// Generated by BUCKLESCRIPT VERSION 4.0.0, PLEASE EDIT WITH CARE
'use strict';

var AnimalBook$ReactTemplate = require("./AnimalBook.bs.js");

function height(t) {
  return t.height;
}

function weight(t) {
  return t.weight;
}

var groupName = "Cat";

var Cat = /* module */[
  /* height */height,
  /* weight */weight,
  /* groupName */groupName
];

var c = {
  height: 100.0,
  weight: 100.0,
  pattern: 1
};

var CatBook = AnimalBook$ReactTemplate.AnimalBook([
      weight,
      height,
      groupName
    ]);

exports.Cat = Cat;
exports.c = c;
exports.CatBook = CatBook;
/* CatBook Not a pure module */
