// Generated by BUCKLESCRIPT VERSION 4.0.0, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var Caml_oo_curry = require("bs-platform/lib/js/caml_oo_curry.js");
var CamlinternalOO = require("bs-platform/lib/js/camlinternalOO.js");
var AnimalBook$ReactTemplate = require("./AnimalBook.bs.js");

var class_tables = [
  0,
  0,
  0
];

function make(height, weight, pattern) {
  if (!class_tables[0]) {
    var $$class = CamlinternalOO.create_table([
          "getLabel",
          "weight",
          "height",
          "pattern"
        ]);
    var env = CamlinternalOO.new_variable($$class, "");
    var ids = CamlinternalOO.get_method_labels($$class, [
          "weight",
          "pattern",
          "height",
          "getLabel"
        ]);
    var weight$1 = ids[0];
    var pattern$1 = ids[1];
    var height$1 = ids[2];
    var getLabel = ids[3];
    CamlinternalOO.set_methods($$class, /* array */[
          height$1,
          (function (self$1) {
              return self$1[env][2];
            }),
          weight$1,
          (function (self$1) {
              return self$1[env][1];
            }),
          getLabel,
          (function (_, _$1) {
              return "\n    $height $weight\n    ";
            }),
          pattern$1,
          (function (self$1) {
              return self$1[env][0];
            })
        ]);
    var env_init = function (env$1) {
      var self = CamlinternalOO.create_object_opt(0, $$class);
      self[env] = env$1;
      return self;
    };
    CamlinternalOO.init_class($$class);
    class_tables[0] = env_init;
  }
  return Curry._1(class_tables[0], [
              pattern,
              weight,
              height
            ]);
}

function height(t) {
  return Caml_oo_curry.js1(38537191, 1, t);
}

function weight(t) {
  return Caml_oo_curry.js1(27685240, 2, t);
}

var groupName = "Dog";

var Dog = /* module */[
  /* height */height,
  /* weight */weight,
  /* groupName */groupName
];

var DogBook = AnimalBook$ReactTemplate.AnimalBook([
      weight,
      height,
      groupName
    ]);

exports.make = make;
exports.Dog = Dog;
exports.DogBook = DogBook;
/* DogBook Not a pure module */
