// Generated by BUCKLESCRIPT VERSION 4.0.0, PLEASE EDIT WITH CARE
'use strict';

var AnimalBook$ReactTemplate = require("./AnimalBook.bs.js");

function height(t) {
  return t[/* height */0];
}

function weight(t) {
  return t[/* weight */1];
}

var groupName = "Dog";

var Dog = /* module */[
  /* height */height,
  /* weight */weight,
  /* groupName */groupName
];

var DogBook = AnimalBook$ReactTemplate.AnimalBook([
      weight,
      height,
      groupName
    ]);

exports.Dog = Dog;
exports.DogBook = DogBook;
/* DogBook Not a pure module */
