// Generated by BUCKLESCRIPT VERSION 4.0.0, PLEASE EDIT WITH CARE
'use strict';

var Caml_exceptions = require("bs-platform/lib/js/caml_exceptions.js");
var Caml_builtin_exceptions = require("bs-platform/lib/js/caml_builtin_exceptions.js");

var Dog = Caml_exceptions.create("Dog-ReactTemplate.Dog");

function make(dog) {
  return [
          Dog,
          dog
        ];
}

function height(t) {
  if (t[0] === Dog) {
    return t[1][/* height */0];
  } else {
    throw [
          Caml_builtin_exceptions.match_failure,
          /* tuple */[
            "Dog.re",
            15,
            4
          ]
        ];
  }
}

function weight(t) {
  if (t[0] === Dog) {
    return t[1][/* height */0];
  } else {
    throw [
          Caml_builtin_exceptions.match_failure,
          /* tuple */[
            "Dog.re",
            19,
            4
          ]
        ];
  }
}

var DogFun = /* module */[
  /* make */make,
  /* height */height,
  /* weight */weight,
  /* groupName */"Dog"
];

var d_001 = /* record */[
  /* height */500.0,
  /* weight */500.0,
  /* pattern */1
];

var d = [
  Dog,
  d_001
];

exports.Dog = Dog;
exports.DogFun = DogFun;
exports.d = d;
/* No side effect */
