// Generated by BUCKLESCRIPT VERSION 4.0.0, PLEASE EDIT WITH CARE
'use strict';


function showAnimalSizeText(animalType) {
  return animalType[0][/* weight */0];
}

exports.showAnimalSizeText = showAnimalSizeText;
/* No side effect */
