// Generated by BUCKLESCRIPT VERSION 4.0.0, PLEASE EDIT WITH CARE
'use strict';

var Cat$ReactTemplate = require("./Cat.bs.js");
var Dog$ReactTemplate = require("./Dog.bs.js");
var Caml_builtin_exceptions = require("bs-platform/lib/js/caml_builtin_exceptions.js");

function showAnimalSizeText(animal) {
  if (animal[0] === Dog$ReactTemplate.Dog) {
    return Dog$ReactTemplate.DogFun[/* height */1](animal);
  } else if (animal[0] === Cat$ReactTemplate.Cat) {
    return Cat$ReactTemplate.CatFun[/* height */1](animal);
  } else {
    throw [
          Caml_builtin_exceptions.match_failure,
          /* tuple */[
            "Sample.re",
            6,
            2
          ]
        ];
  }
}

console.log(showAnimalSizeText(Dog$ReactTemplate.d));

console.log(showAnimalSizeText(Cat$ReactTemplate.c));

exports.showAnimalSizeText = showAnimalSizeText;
/*  Not a pure module */
