// Generated by BUCKLESCRIPT VERSION 4.0.0, PLEASE EDIT WITH CARE
'use strict';

var Caml_oo_curry = require("bs-platform/lib/js/caml_oo_curry.js");
var Dog$ReactTemplate = require("./Dog.bs.js");

function showAnimalSizeText(animalType) {
  console.log(Caml_oo_curry.js2(-813294210, 1, animalType, /* () */0));
  return /* () */0;
}

var catText = showAnimalSizeText(Dog$ReactTemplate.make(100.0, 10.0, 3));

exports.showAnimalSizeText = showAnimalSizeText;
exports.catText = catText;
/* catText Not a pure module */
